# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym_J_lXdKwrVCLN2cgKVnTg85lh9Qe4b
"""

import streamlit as st
from transformers import BlipProcessor, BlipForConditionalGeneration, BlipForQuestionAnswering
from gtts import gTTS
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="AI See & Speak")

@st.cache_resource
def load_models():
    """Loads all models once and caches them across reruns."""
    processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
    model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
    vqa_processor = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
    vqa_model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")
    return processor, model, vqa_processor, vqa_model

processor, model, vqa_processor, vqa_model = load_models()


def generate_caption(image, style="simple"):
    prompts = {
        "simple": "",
        "detailed": "a detailed description of",
        "funny": "a funny caption for this image showing"
    }
    prompt = prompts.get(style, "")
    if prompt:
        inputs = processor(image, prompt, return_tensors="pt")
    else:
        inputs = processor(image, return_tensors="pt")
    output = model.generate(**inputs, max_length=60)
    return processor.decode(output[0], skip_special_tokens=True)


def answer_question(image, question):
    inputs = vqa_processor(image, question, return_tensors="pt")
    output = vqa_model.generate(**inputs, max_new_tokens=20)
    return vqa_processor.decode(output[0], skip_special_tokens=True)


def compute_saliency_map(image, caption):
    inputs = processor(image, return_tensors="pt")
    pixel_values = inputs["pixel_values"]
    pixel_values.requires_grad_()
    text_inputs = processor(text=caption, return_tensors="pt")
    outputs = model(
        pixel_values=pixel_values,
        input_ids=text_inputs["input_ids"],
        labels=text_inputs["input_ids"]
    )
    outputs.loss.backward()
    saliency = pixel_values.grad.abs().squeeze().max(dim=0)[0]
    return saliency.detach().numpy()


# --- UI ---
st.title("AI See & Speak")
st.write("Upload an image, then get a spoken description or ask a question about it.")

uploaded_file = st.file_uploader("Upload Image", type=["jpg", "jpeg", "png"])

mode = st.radio("Mode", ["Describe", "Ask"])

style = "simple"
question = ""

if mode == "Describe":
    style = st.radio("Caption Style", ["simple", "detailed", "funny"])
else:
    question = st.text_input("Question", placeholder="e.g. What color is his suit?")

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    st.image(image, caption="Uploaded Image", use_container_width=True)

    if st.button("Run"):
        with st.spinner("Processing..."):
            if mode == "Describe":
                text_output = generate_caption(image, style=style)
                caption_for_saliency = text_output
            else:
                text_output = answer_question(image, question)
                caption_for_saliency = generate_caption(image)

            st.subheader("Result")
            st.write(text_output)

            # Speech
            tts = gTTS(text=text_output, lang='en')
            audio_path = "output.mp3"
            tts.save(audio_path)
            st.audio(audio_path)

            # Saliency map
            saliency = compute_saliency_map(image, caption_for_saliency)
            saliency_img = Image.fromarray(
                (saliency / saliency.max() * 255).astype(np.uint8)
            ).resize(image.size, resample=Image.BILINEAR)

            fig, ax = plt.subplots(figsize=(6, 6))
            ax.imshow(image)
            ax.imshow(saliency_img, cmap='jet', alpha=0.5)
            ax.axis('off')
            st.subheader("What the model focused on")
            st.pyplot(fig)

